### ISSUE TITLE
How to configure set points for CPE? / Error: Please provide a yaml-input file.

### ISSUE THREAD

**Issue by StefanPofahl** [j-zimmermann/ImpedanceFitter#9]
Attached my example to fit a circuit model which include 3 CPE elements. 
Unfortunately, the script is not executed as expected, where is the issue?
```
# --- impedancefitter-example to optimize parameters of given equivalent circuit structure: --------------------------------
import os
import impedancefitter as impfit
import numpy as np
import pandas

# --- Sample impedance values and corresponding frequency vector: ----------------------------------------------------------
list_frequ = [0.0199553, 0.0251206, 0.0316296, 0.0398258, 0.0501337, 0.0631739, 0.0794492, 0.1001603, 0.1260081, 
    0.1588983, 0.2003205, 0.2520161, 0.316723, 0.400641, 0.5040323, 0.6334459, 0.7923428, 0.999041, 1.266892, 
    1.584686, 1.998082, 2.504006, 3.158693, 3.945707, 5.008013, 6.317385, 7.944915, 9.93114, 12.40079, 15.625, 
    19.86229, 24.93351, 31.25, 38.42213, 50.22321, 63.3446, 79.00281, 100.4464, 125.558, 158.3615, 198.6229, 
    252.4038, 315.5048, 397.9953, 505.5147, 627.7902, 796.875, 998.264, 1265.625, 1577.524, 1976.103, 2527.573]
frequencies = np.array(list_frequ)

list_z_real = [0.0192023, 0.0191242, 0.0190921, 0.0190038, 0.0189117, 0.0188934, 0.0188256, 0.0187806, 0.0187788, 
    0.018721, 0.0186957, 0.0186338, 0.0185409, 0.0184303, 0.0182806, 0.0181321, 0.0179509, 0.017754, 0.0175502, 
    0.0173766, 0.0171844, 0.0169962, 0.0167821, 0.0165568, 0.0162894, 0.0160016, 0.0156597, 0.0152661, 0.0147982, 
    0.0142456, 0.0136019, 0.0129721, 0.0123483, 0.0118009, 0.011152, 0.010654, 0.0102355, 0.0098378, 0.0095112, 
    0.0092073, 0.0089405, 0.0086829, 0.0084644, 0.0082576, 0.0080616, 0.0078987, 0.0077369, 0.0075978, 0.0074675, 
    0.0073608, 0.0072638, 0.0071759]
z_real = np.array(list_z_real)

list_z_imag = [6.406656e-6, -8.276627e-5, -0.0001089, -0.0001645, -0.0002133, -0.0002243, -0.0002757, -0.0003211, 
    -0.0003745, -0.0004454, -0.0005298, -0.0006171, -0.0007205, -0.0008409, -0.0009458, -0.0010522, -0.0011472, 
    -0.0012429, -0.0013275, -0.0014186, -0.0015215, -0.0016264, -0.0017693, -0.0019212, -0.0021114, -0.0023279, 
    -0.002562, -0.0027968, -0.0030195, -0.0032134, -0.00335, -0.0033938, -0.0033619, -0.0032698, -0.0030826, 
    -0.0028835, -0.0026797, -0.0024579, -0.0022581, -0.0020614, -0.0018805, -0.0017002, -0.0015397, -0.0013784, 
    -0.0012167, -0.0010697, -0.0009059, -0.0007438, -0.0005658, -0.0003879, -0.0001883, 5.594581e-5]
z_imag = np.array(list_z_imag)

# --- export data to file: -------------------------------------------------------------------------------------------------
data_ = {'freq': frequencies, 'real': z_real, 'imag': z_imag}
# write data to csv file
df = pandas.DataFrame(data= data_)
df.to_csv('test.csv', index= False)
print('current directory: ', os.getcwd())
# --- read back from file and delete "test.csv":
fitter = impfit.Fitter('CSV', LogLevel= 'DEBUG', show= True)
os.remove('test.csv')


# --- specified equivalent circuit and initial values for specified equivalent circuit: ------------------------------------
circuit_model = 'R_f1 + L_f1 + parallel(CPE_f1, R_f2) + parallel(CPE_f2, R_f3) + parallel(CPE_f3, R_f4)'

# R_f1 + L_f1
Rf1 = 1.8316292335542916e-6
Lf1 = 3.841697220081128e-8

# CPE_f1, R_f2
CPEf1 = [122.33692766836256, 0.016474727737511817]
Rf2 = 4.1889281168951976e8

# CPE_f2, R_f3
CPEf2 = [3.197631131861641,        0.6615361109814648]
Rf3 = 0.01066085025420658

# CPE_f3, R_f4 
CPEf3 = [4.052025887940292e7,      0.0005986533916707004]
Rf4 = 6.284668546378043e8

parameters = {'R_f1': Rf1, 'L_f1': Lf1, 'CPE_f1': CPEf1, 'R_f2': Rf2, 'CPE_f2': CPEf2, 'R_f3': Rf3, 'CPE_f3': CPEf3, 'R_f4': Rf4}

# --- fit parameters: -----------------------------------------------------------------------------------------------------
fitter.run(circuit_model, parameters)
```
Error message:

```
>>> fitter.run(circuit_model, parameters)
circuit: ['R_f1', '+', 'L_f1', '+', ['CPE_f1', ',', 'R_f2'], '+', ['CPE_f2', ',', 'R_f3'], '+', ['CPE_f3', ',', 'R_f4']]
circuit: ['CPE_f1', ',', 'R_f2']
circuit: ['CPE_f2', ',', 'R_f3']
Created composite model <lmfit.Model: ((((Model(Z_R, prefix='f1_') + Model(Z_L, prefix='f1_')) + (Model(cpe_model, prefix='f1_') <function parallel at 0x000001BDB1C43820> Model(Z_R, prefix='f2_'))) + (Model(cpe_model, prefix='f2_') <function parallel at 0x000001BDB1C43820> Model(Z_R, prefix='f3_'))) + (Model(cpe_model, prefix='f3_') <function parallel at 0x000001BDB1C43820> Model(Z_R, prefix='f4_')))>
Please provide a yaml-input file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\impedancefitter\fitter.py", line 476, in run
    self.model_parameters = self._initialize_parameters(self.model, self.parameters, self.emcee_tag, self.weighting_model)
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\impedancefitter\fitter.py", line 359, in _initialize_parameters
    return set_parameters(model, parameterdict=parameters,
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\impedancefitter\utils.py", line 322, in set_parameters
    infile = open('input.yaml', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'input.yaml'
>>> & C:/bin/WPy64-3980/python-3.9.8.amd64/python.exe c:/data/git_repos/hycenta_stefan_pofahl/python/examples/equivalent_circuit_fit/package_impedancefitter/example_optimize_circuit_params_via_impedancefitter.py
  File "<stdin>", line 1
    & C:/bin/WPy64-3980/python-3.9.8.amd64/python.exe c:/data/git_repos/hycenta_stefan_pofahl/python/examples/equivalent_circuit_fit/package_impedancefitter/example_optimize_circuit_params_via_impedancefitter.py
    ^
SyntaxError: invalid syntax
>>>
```

**Comment by StefanPofahl** [comment]
Meanwhile I figured out, how to set up the `lmfit`-compatible dict via:
```
from lmfit import Parameters
[...]
parameters = Parameters()
parameters.add('f1_R',      value = f1R)
parameters.add('f2_L',      value = f2L)
parameters.add('f3_k',      value = f3k)
parameters.add('f3_alpha',  value = f3alpha)
[...]
```
unfortunately, the `input.yaml` issue is still there.
Here my new script:
```
import os
import impedancefitter as impfit
import numpy as np
import pandas
from lmfit import Parameters

# --- Sample impedance values and corresponding frequency vector: ----------------------------------------------------------
# --- (measured data from Matthias Ranz)
list_frequ = [0.0199553, 0.0251206, 0.0316296, 0.0398258, 0.0501337, 0.0631739, 0.0794492, 0.1001603, 0.1260081, 
    0.1588983, 0.2003205, 0.2520161, 0.316723, 0.400641, 0.5040323, 0.6334459, 0.7923428, 0.999041, 1.266892, 
    1.584686, 1.998082, 2.504006, 3.158693, 3.945707, 5.008013, 6.317385, 7.944915, 9.93114, 12.40079, 15.625, 
    19.86229, 24.93351, 31.25, 38.42213, 50.22321, 63.3446, 79.00281, 100.4464, 125.558, 158.3615, 198.6229, 
    252.4038, 315.5048, 397.9953, 505.5147, 627.7902, 796.875, 998.264, 1265.625, 1577.524, 1976.103, 2527.573]
frequencies = np.array(list_frequ)

list_z_real = [0.0192023, 0.0191242, 0.0190921, 0.0190038, 0.0189117, 0.0188934, 0.0188256, 0.0187806, 0.0187788, 
    0.018721, 0.0186957, 0.0186338, 0.0185409, 0.0184303, 0.0182806, 0.0181321, 0.0179509, 0.017754, 0.0175502, 
    0.0173766, 0.0171844, 0.0169962, 0.0167821, 0.0165568, 0.0162894, 0.0160016, 0.0156597, 0.0152661, 0.0147982, 
    0.0142456, 0.0136019, 0.0129721, 0.0123483, 0.0118009, 0.011152, 0.010654, 0.0102355, 0.0098378, 0.0095112, 
    0.0092073, 0.0089405, 0.0086829, 0.0084644, 0.0082576, 0.0080616, 0.0078987, 0.0077369, 0.0075978, 0.0074675, 
    0.0073608, 0.0072638, 0.0071759]
z_real = np.array(list_z_real)

list_z_imag = [6.406656e-6, -8.276627e-5, -0.0001089, -0.0001645, -0.0002133, -0.0002243, -0.0002757, -0.0003211, 
    -0.0003745, -0.0004454, -0.0005298, -0.0006171, -0.0007205, -0.0008409, -0.0009458, -0.0010522, -0.0011472, 
    -0.0012429, -0.0013275, -0.0014186, -0.0015215, -0.0016264, -0.0017693, -0.0019212, -0.0021114, -0.0023279, 
    -0.002562, -0.0027968, -0.0030195, -0.0032134, -0.00335, -0.0033938, -0.0033619, -0.0032698, -0.0030826, 
    -0.0028835, -0.0026797, -0.0024579, -0.0022581, -0.0020614, -0.0018805, -0.0017002, -0.0015397, -0.0013784, 
    -0.0012167, -0.0010697, -0.0009059, -0.0007438, -0.0005658, -0.0003879, -0.0001883, 5.594581e-5]
z_imag = np.array(list_z_imag)

# --- export data to file, read back and delete: ---------------------------------------------------------------------------
data_ = {'freq': frequencies, 'real': z_real, 'imag': z_imag}
# write data to csv file
df = pandas.DataFrame(data= data_)
df.to_csv('test.csv', index= False)
print('current directory: ', os.getcwd())
# --- read back from file and delete "test.csv":
fitter = impfit.Fitter('CSV', LogLevel= 'DEBUG', show= True)
os.remove('test.csv')

# --- specified equivalent circuit and initial values for specified equivalent circuit: ------------------------------------
# EquivalentCircuits_jl model spefication: 'R1-L2-[P3,R4]-[P5,R6]-[P7,R8]'
circuit_model = 'R_f1 + L_f2 + parallel(CPE_f3, R_f4) + parallel(CPE_f5, R_f6) + parallel(CPE_f7, R_f8)'
# --- draw equivalent circuit model:
# impfit.draw_scheme(circuit_model)

# f1_R + f2_L
f1R         = 1.8316292335542916e-6
f2L         = 3.841697220081128e-8

# f3_k, f3_alpha, f4_R
f3_k        = 122.33692766836256
f3_alpha    = 0.016474727737511817
f4R         = 4.1889281168951976e8

# f5_k, f5_alpha, f6_R
f5k         = 3.197631131861641
f5alpha     = 0.6615361109814648
f6R         = 0.01066085025420658
# f7_k, f7_alpha, f8_R
f7k         = 4.052025887940292e7
f7alpha     = 0.0005986533916707004
f8R         = 6.284668546378043e8
parameters = Parameters()
parameters.add('f1_R',      value = f1R)
parameters.add('f2_L',      value = f2L)
parameters.add('f3_k',      value = f3_k)
parameters.add('f3_alpha',  value = f3_alpha)
parameters.add('f4_R',      value = f4R)
parameters.add('f5_k',      value = f5k)
parameters.add('f5_alpha',  value = f5alpha)
parameters.add('f6_R',      value = f6R)
parameters.add('f7_k',      value = f7k)
parameters.add('f7_alpha',  value = f7alpha)
parameters.add('f8_R',      value = f8R)

# --- simulate impdance: ---------------------------------------------------------------------------------------------------
lmfit_model = impfit.get_equivalent_circuit_model(circuit_model)
Z = lmfit_model.eval(omega=2. * np.pi * frequencies, params= parameters)
# --- fit parameters: -----------------------------------------------------------------------------------------------------
fitter.run(circuit_model, parameters)
```

**Comment by j-zimmermann** [comment]
There's just a two issues with your code:
* The `parameters` that you pass to the fitter should be a nested dictionary.
* Please use kwarg there, i.e. `fitter.run(circuit_model, parameters=parameters)`

Otherwise, you have to supply the parameters via the `input.yaml` file.
There is also an example to show how the fitting process is intended:
https://impedancefitter.readthedocs.io/en/latest/examples/fitting.html

Please let me know if you have any suggestions for improvement.

**Comment by StefanPofahl** [comment]
Thank you for your quick answer! I found a link to the definition of a lmfit-compatible dict on the following page:
[lmfit-parameters](https://lmfit.github.io/lmfit-py/parameters.html).
I have tried to correct the definition of the dict, but there is still an issue, one key for one R-element seem to be missing:
```
[...]
parameters =   {'f1_R':     { 'value': f1R},
                'f2_L':     { 'value': f2L},
                'f3_k':     { 'value': f3k},
                'f3_alpha': { 'value': f3alpha},
                'f4_R':     { 'value': f4R},
                'f5_k':     { 'value': f5k},
                'f5_alpha': { 'value': f5alpha},
                'f6_R':     { 'value': f6R},
                'f7_k':     { 'value': f7k},
                'f7_alpha': { 'value': f7alpha},
                'f8_R':     { 'value': f8R},
                }

# --- simulate impdance: ---------------------------------------------------------------------------------------------------
lmfit_model = impfit.get_equivalent_circuit_model(circuit_model)
Z = lmfit_model.eval(omega=2. * np.pi * frequencies, parameters= parameters)
# --- fit parameters: -----------------------------------------------------------------------------------------------------
# function "run()": https://impedancefitter.readthedocs.io/en/v2.0.0/fitting.html#impedancefitter.fitter.Fitter.run
fitter.run(circuit_model, parameters)
```

The corresponding message is:
```
>>> lmfit_model = impfit.get_equivalent_circuit_model(circuit_model)
    return self.op(self.left.eval(params=params, **kwargs),
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 1161, in eval
    return self.op(self.left.eval(params=params, **kwargs),
  [Previous line repeated 1 more time]
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 871, in eval
    return self.func(**self.make_funcargs(params, kwargs))
TypeError: Z_R() missing 1 required positional argument: 'R'
>>> parameters =   {'f1_R':     { 'value': f1R},
...                 'f3_k':     { 'value': f3k},
...                 'f3_alpha': { 'value': f3alpha},
...                 'f4_R':     { 'value': f4R},
...                 'f5_k':     { 'value': f5k},
...                 'f5_alpha': { 'value': f5alpha},
...                 'f6_R':     { 'value': f6R},
...                 'f7_k':     { 'value': f7k},
...                 'f7_alpha': { 'value': f7alpha},
...                 'f8_R':     { 'value': f8R},
...                 }
>>>
>>> lmfit_model = impfit.get_equivalent_circuit_model(circuit_model)
circuit: ['CPE_f3', ',', 'R_f4']
circuit: ['CPE_f5', ',', 'R_f6']
circuit: ['CPE_f7', ',', 'R_f8']
Created composite model <lmfit.Model: ((((Model(Z_R, prefix='f1_') + Model(Z_L, prefix='f2_')) + (Model(cpe_model, prefix='f3_') <function parallel at 0x0000016C522E7670> Model(Z_R, prefix='f4_'))) + (Model(cpe_model, prefix='f5_') <function parallel at 0x0000016C522E7670> Model(Z_R, prefix='f6_'))) + (Model(cpe_model, prefix='f7_') <function parallel at 0x0000016C522E7670> Model(Z_R, prefix='f8_')))>
>>> Z = lmfit_model.eval(omega=2. * np.pi * frequencies, parameters= parameters)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 1161, in eval
    return self.op(self.left.eval(params=params, **kwargs),
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 1161, in eval
    return self.op(self.left.eval(params=params, **kwargs),
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 1161, in eval
    return self.op(self.left.eval(params=params, **kwargs),
  [Previous line repeated 1 more time]
  File "C:\bin\WPy64-3980\python-3.9.8.amd64\lib\site-packages\lmfit\model.py", line 871, in eval
    return self.func(**self.make_funcargs(params, kwargs))
TypeError: Z_R() missing 1 required positional argument: 'R'
```

**Comment by j-zimmermann** [comment]
I ran the following code with the latest release and had no problem. I don't use Windows though.
Unfortunately, the circuit evaluation currently takes a different `dict` than the fitter itself.
I haven't yet written a wrapper around it. I added it to the TODO list.
In the script, I also customised the solver and added a LinKK test to check the validity of your data.

```
import os
import impedancefitter as impfit
import numpy as np
import pandas
from lmfit import Parameters

# --- Sample impedance values and corresponding frequency vector: ----------------------------------------------------------
# --- (measured data from Matthias Ranz)
list_frequ = [0.0199553, 0.0251206, 0.0316296, 0.0398258, 0.0501337, 0.0631739, 0.0794492, 0.1001603, 0.1260081, 
    0.1588983, 0.2003205, 0.2520161, 0.316723, 0.400641, 0.5040323, 0.6334459, 0.7923428, 0.999041, 1.266892, 
    1.584686, 1.998082, 2.504006, 3.158693, 3.945707, 5.008013, 6.317385, 7.944915, 9.93114, 12.40079, 15.625, 
    19.86229, 24.93351, 31.25, 38.42213, 50.22321, 63.3446, 79.00281, 100.4464, 125.558, 158.3615, 198.6229, 
    252.4038, 315.5048, 397.9953, 505.5147, 627.7902, 796.875, 998.264, 1265.625, 1577.524, 1976.103, 2527.573]
frequencies = np.array(list_frequ)

list_z_real = [0.0192023, 0.0191242, 0.0190921, 0.0190038, 0.0189117, 0.0188934, 0.0188256, 0.0187806, 0.0187788, 
    0.018721, 0.0186957, 0.0186338, 0.0185409, 0.0184303, 0.0182806, 0.0181321, 0.0179509, 0.017754, 0.0175502, 
    0.0173766, 0.0171844, 0.0169962, 0.0167821, 0.0165568, 0.0162894, 0.0160016, 0.0156597, 0.0152661, 0.0147982, 
    0.0142456, 0.0136019, 0.0129721, 0.0123483, 0.0118009, 0.011152, 0.010654, 0.0102355, 0.0098378, 0.0095112, 
    0.0092073, 0.0089405, 0.0086829, 0.0084644, 0.0082576, 0.0080616, 0.0078987, 0.0077369, 0.0075978, 0.0074675, 
    0.0073608, 0.0072638, 0.0071759]
z_real = np.array(list_z_real)

list_z_imag = [6.406656e-6, -8.276627e-5, -0.0001089, -0.0001645, -0.0002133, -0.0002243, -0.0002757, -0.0003211, 
    -0.0003745, -0.0004454, -0.0005298, -0.0006171, -0.0007205, -0.0008409, -0.0009458, -0.0010522, -0.0011472, 
    -0.0012429, -0.0013275, -0.0014186, -0.0015215, -0.0016264, -0.0017693, -0.0019212, -0.0021114, -0.0023279, 
    -0.002562, -0.0027968, -0.0030195, -0.0032134, -0.00335, -0.0033938, -0.0033619, -0.0032698, -0.0030826, 
    -0.0028835, -0.0026797, -0.0024579, -0.0022581, -0.0020614, -0.0018805, -0.0017002, -0.0015397, -0.0013784, 
    -0.0012167, -0.0010697, -0.0009059, -0.0007438, -0.0005658, -0.0003879, -0.0001883, 5.594581e-5]
z_imag = np.array(list_z_imag)

# --- export data to file, read back and delete: ---------------------------------------------------------------------------
data_ = {'freq': frequencies, 'real': z_real, 'imag': z_imag}
# write data to csv file
df = pandas.DataFrame(data= data_)
df.to_csv('test.csv', index= False)
print('current directory: ', os.getcwd())
# --- read back from file and delete "test.csv":
fitter = impfit.Fitter('CSV', LogLevel= 'DEBUG', show= True)
os.remove('test.csv')

# --- specified equivalent circuit and initial values for specified equivalent circuit: ------------------------------------
# EquivalentCircuits_jl model spefication: 'R1-L2-[P3,R4]-[P5,R6]-[P7,R8]'
circuit_model = 'R_f1 + L_f2 + parallel(CPE_f3, R_f4) + parallel(CPE_f5, R_f6) + parallel(CPE_f7, R_f8)'
# --- draw equivalent circuit model:
# impfit.draw_scheme(circuit_model)

# f1_R + f2_L
f1R         = 1.8316292335542916e-6
f2L         = 3.841697220081128e-8

# f3_k, f3_alpha, f4_R
f3k        = 1. / 122.33692766836256
f3alpha    = 0.016474727737511817
f4R         = 4.1889281168951976e8

# f5_k, f5_alpha, f6_R
f5k         = 1. / 3.197631131861641
f5alpha     = 0.6615361109814648
f6R         = 0.01066085025420658
# f7_k, f7_alpha, f8_R
f7k         = 1. / 4.052025887940292e7
f7alpha     = 0.0005986533916707004
f8R         = 6.284668546378043e8
parameters = Parameters()
parameters.add('f1_R',      value = f1R)
parameters.add('f2_L',      value = f2L)
parameters.add('f3_k',      value = f3k)
parameters.add('f3_alpha',  value = f3alpha)
parameters.add('f4_R',      value = f4R)
parameters.add('f5_k',      value = f5k)
parameters.add('f5_alpha',  value = f5alpha)
parameters.add('f6_R',      value = f6R)
parameters.add('f7_k',      value = f7k)
parameters.add('f7_alpha',  value = f7alpha)
parameters.add('f8_R',      value = f8R)
# --- simulate impdance: ---------------------------------------------------------------------------------------------------
lmfit_model = impfit.get_equivalent_circuit_model(circuit_model)
Z = lmfit_model.eval(omega=2. * np.pi * frequencies, **parameters)
parameters =   {'f1_R':     { 'value': f1R},
                'f2_L':     { 'value': f2L},
                'f3_k':     { 'value': f3k},
                'f3_alpha': { 'value': f3alpha},
                'f4_R':     { 'value': f4R},
                'f5_k':     { 'value': f5k},
                'f5_alpha': { 'value': f5alpha},
                'f6_R':     { 'value': f6R},
                'f7_k':     { 'value': f7k},
                'f7_alpha': { 'value': f7alpha},
                'f8_R':     { 'value': f8R},
                }


# Uncomment to plot the data
# fitter.visualize_data()
# LinKK test
_, _, _ = fitter.linkk_test()
_, _, _ = fitter.linkk_test(inductance=True)
# --- fit parameters: -----------------------------------------------------------------------------------------------------
# function "run()": https://impedancefitter.readthedocs.io/en/v2.0.0/fitting.html#impedancefitter.fitter.Fitter.run
fitter.run(circuit_model, parameters=parameters, report=True, show=True)

# customise fitter
parameters =   {'f1_R':     { 'value': f1R, "vary": False},
                'f2_L':     { 'value': f2L},
                'f3_k':     { 'value': f3k},
                'f3_alpha': { 'value': f3alpha},
                'f4_R':     { 'value': f4R, "vary": False},
                'f5_k':     { 'value': f5k},
                'f5_alpha': { 'value': f5alpha},
                'f6_R':     { 'value': f6R, "vary": False},
                'f7_k':     { 'value': f7k},
                'f7_alpha': { 'value': f7alpha * 1e3},
                'f8_R':     { 'value': f8R, "vary": False},
                }
solver = "nelder"
fitter.run(circuit_model, parameters=parameters,
           solver=solver,
           # solver_kwargs=solver_kwargs,  # to customise solver
           report=True, show=True)
```

**Comment by j-zimmermann** [comment]
In this directory, there are some slides to explain the ideas behind the used algorithms: https://github.com/j-zimmermann/ImpedanceFitter/tree/master/introduction
Again, feedback on the slides and the software are highly appreciated.

**Comment by StefanPofahl** [comment]
Thanks for your code snipped! 
Does your answer mean, my code is correct and it might be a MS-Windows issue?
Or a version issue? Do I need the master-version? And if this is the case, how do I install the master version?
Below the line `# customize fitter` you added `'vary': False` for R-elements? 
Does it mean, the R-elements are not fitted?

**Comment by j-zimmermann** [comment]
You're welcome :)
Your code looks correct and I could not reproduce the error. Thus, I though about a Windows issue.
You can upgrade via pip to the latest version, it is even with the master branch.

Indeed I fixed the `R` values. Otherwise, the fitting algorithm converged but uncertainties could not be estimated.
This indicates overfitting and so I fixed certain values.

**Comment by StefanPofahl** [comment]
Now my plan is, to compare the fit results achieved with different fit-parameters.
One quality criteria might be the mean of the distances of the two impedance-vectors:
`mean(abs(Z-measured Z-fit_result))`. 
One idea is, to evaluate/simulate the impedance values via `lmfit_model.eval()`.
Another option is to find the impedance values of the last optimization iteration of 
the `fitter.run()`-function.
But I am not sure, if my code is correct:
```
Z_fitresult = fitter.fittedValues.best_fit
Z_data = (z_real + 1j * z_imag)
Q = np.mean(abs(Z_fitresult - Z_data))
``` 
Maybe a similar scalar quality criteria is already nested in the object `fitter`?
Regards,
Stefan

P.S.:
You invited my to give a feedback, for a new-comer it would be nice to integrate into your example
a case with a CPE-element to understand better the concept how to build the parameter dict for the 
`lmfit_model.eval()` and `fitter.run()` function.
P.P.S.:
You asked for other data interfaces of the `impedancefitter.Fitter()`-function, it would be nice,
to know how to pass the impedance data vectors `frequencies` and `Z-data` directly, without writing 
into a CSV, read back the data and delete the data file.
P.P.P.S.:
Maybe it is useful to add my example to your collection of examples and add a comment about the 
difference between the CPE model implemented in `impedancefitter.py` versus `impedance.py`.

**Comment by StefanPofahl** [comment]
> Your code looks correct and I could not reproduce the error.
P.S.:
at home I work under linux and the strange error-message is gone ...

**Comment by StefanPofahl** [comment]
Where can I find the fitted parameters in the object `fitter` in a form that I can feed to a second run of `fitter.run()`,
eg. exclude R-elements from optimization in the first ran an do a second optimization where all parameters are set to `"vary": True`

**Comment by j-zimmermann** [comment]
Regarding the quality criteria: you can use your approach. Built-in estimates are, for example, available via:
`fitter.model_results["test.csv_0"].chisqr`

Thanks for your suggestions! I will include such an example. 
However, I currently do not plan to change the Fitter function because we mainly use ImpedanceFitter to batch-process a lot of existing impedance files.
However, I will probably implement a utility function to prepare the impedance files.

> Where can I find the fitted parameters in the object `fitter` in a form that I can feed to a second run of `fitter.run()`, eg. exclude R-elements from optimization in the first ran an do a second optimization where all parameters are set to `"vary": True`

You would do this by editing the `parameters` dictionary.
E.g. (not tested, treat it as pseudocode):
```
for p, value in fitter.fit_data['test.csv_0'].items():
    parameters[p]["value"] = value
    if "R" in p:
         parameters[p]["vary"] = True
```

**Comment by StefanPofahl** [comment]
Thanks :-)
This hidden features are not easy to understand :-)
To compare different measurements with varying number of points, a quality criteria the calculates the mean of the deviations 
is better suited.
One idea is to do the optimization step by step, here a function, coded by a colleague of mine, to exclude specific 
parameter-types from optimization:
```
def nest_dict(dict_in, fix_key=''):
    """Function which takes a dictionary object whos keys only have one value and
    returns a dictionary object with the origional keys remaining but the value now being a nested dictionary with the initial
    values now being indexed by the key 'value'

    Input:
    dictionary object 
    fix_key: optional, default empty string, one of the parameter strings: 'R', 'L', 'C', 'k', 'alpha', etc.

    Output:
    dictionary object
    """

    dict_out = {}
    keys = list(dict_in.keys())
    for key in keys: 
        dict_out[key] = {'value': dict_in[key]}
        if fix_key == key.split('_')[-1]: 
            dict_out[key]['vary'] = False
    return dict_out
```
